import LoginTemplate from '@/src/modules/account/templates/login-template'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Login',
  description: 'Generated by create next app'
}

export default function Login() {
  return (
    <main className=''>
      <LoginTemplate />
    </main>
  )
}
