import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Register",
  description: "Generated by create next app",
};

export default function Login() {
  return (
    <main className="">
      <p>Register</p>
    </main>
  );
}
