import type { Metadata } from 'next'
import './globals.css'
import Providers from '../modules/providers'

export const metadata: Metadata = {
  title: 'Homepage',
  description: 'Generated by create next app',
  authors: [{ name: 'Lifesup', url: 'https://lifesup.com.vn' }]
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <main>
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  )
}
