import type { Metadata } from 'next'
import './globals.css'
import Providers from '../modules/providers'

export const metadata: Metadata = {
  title: 'Spa Malay',
  description: 'Generated by create next app',
  openGraph: {
    title: 'Spa Malay',
    description: 'Help you to relax and feel better',
    type: 'website',
    images: ['https://raw.githubusercontent.com/phamlam2k/spa-malay/main/public/images/spa_intro.webp']
  }
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <main>
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  )
}
